# Generated by Django 4.2.1 on 2023-06-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="cv",
            field=models.FileField(upload_to="static"),
        ),
    ]
