# Generated by Django 4.2.1 on 2023-06-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_cv_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="cv",
            field=models.FileField(upload_to="static/cv/"),
        ),
    ]
