# Generated by Django 3.2.19 on 2023-07-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_cv_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='portfolio/')),
            ],
        ),
    ]
