# Generated by Django 3.2.19 on 2023-08-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
