# Generated by Django 3.2.19 on 2023-08-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='portfolio',
        ),
    ]
