# Generated by Django 3.2.19 on 2023-08-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_portfolio_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='allimage',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('all_image', models.ImageField(default='', upload_to='portfolio')),
            ],
        ),
    ]
